python/django/django-book-mysite-sample/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

python/django/django-book-mysite-sample/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.detail, name='detail'),
    path('checkout/', views.checkout, name='checkout'),
]

python/django/django-book-mysite-sample/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.signals import user_logged_in


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta(object):
        db_table = 'custom_user'

    login_count = models.IntegerField(verbose_name='ログイン回数', default=0)

    def post_login(self):
        """ログイン後処理"""
        # ログイン回数を増やす
        self.login_count += 1
        self.save()


# def update_login_count(sender, user, **kwargs):
#     """
#     A signal receiver which updates the last_login date for
#     the user logging in.
#     """
#     user.login_count += 1
#     user.save(update_fields=['login_count'])
#
#
# user_logged_in.connect(update_login_count)

python/django/django-book-mysite-sample/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ObjectDoesNotExist

from .models import CustomUser


class RegisterForm(forms.ModelForm):
    """ユーザー登録画面用のフォーム"""

    class Meta:
        # 利用するモデルクラスを指定
        model = CustomUser
        # 利用するモデルのフィールドを指定
        fields = ('username', 'email', 'password',)
        # ウィジェットを上書き
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'ユーザー名'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'パスワード'}),
        }

    password2 = forms.CharField(
        label='確認用パスワード',
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': '確認用パスワード'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # フィールドの属性を書き換え
        self.fields['email'].required = True
        self.fields['email'].widget.attrs = {'placeholder': 'メールアドレス'}

    def clean_username(self):
        value = self.cleaned_data['username']
        if len(value) < 3:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 3})
        return value

    def clean_email(self):
        value = self.cleaned_data['email']
        return value

    def clean_password(self):
        value = self.cleaned_data['password']
        return value

    def clean(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError("パスワードと確認用パスワードが合致しません")
        # ユニーク制約を自動でバリデーションしてほしい場合は super の clean() を明示的に呼び出す
        super().clean()


class LoginForm(forms.Form):
    """ログイン画面用のフォーム"""

    username = UsernameField(
        label='ユーザー名',
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'ユーザー名', 'autofocus': True}),
    )

    password = forms.CharField(
        label='パスワード',
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'パスワード'}, render_value=True),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user_cache = None

    def clean_password(self):
        value = self.cleaned_data['password']
        return value

    def clean_username(self):
        value = self.cleaned_data['username']
        if len(value) < 3:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 3})
        return value

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        try:
            user = get_user_model().objects.get(username=username)
        except ObjectDoesNotExist:
            raise forms.ValidationError("正しいユーザー名を入力してください")
        # パスワードはハッシュ化されて保存されているので平文での検索はできない
        if not user.check_password(password):
            raise forms.ValidationError("正しいユーザー名とパスワードを入力してください")
        # 取得したユーザーオブジェクトを使い回せるように内部に保持しておく
        self.user_cache = user

    def get_user(self):
        return self.user_cache


class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {'placeholder': 'ユーザー名'}
        self.fields['email'].required = True
        self.fields['email'].widget.attrs = {'placeholder': 'メールアドレス'}
        # self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': 'パスワード'}, render_value=True)
        self.fields['last_name'].widget.attrs = {'placeholder': '苗字'}
        self.fields['first_name'].widget.attrs = {'placeholder': '名前'}

    def clean_username(self):
        value = self.cleaned_data['username']
        return value

    def clean_email(self):
        value = self.cleaned_data['email']
        return value

python/django/django-book-mysite-sample/accounts/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from .forms import LoginForm, RegisterForm, ProfileForm

logger = logging.getLogger(__name__)


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        # すでにログインしている場合はショップ画面へリダイレクト
        if request.user.is_authenticated:
            return redirect(reverse('shop:index'))

        context = {
            'form': RegisterForm(),
        }
        return render(request, 'accounts/register.html', context)

    def post(self, request, *args, **kwargs):
        logger.info("You're in post!!!")

        # リクエストからフォームを作成
        form = RegisterForm(request.POST)
        # バリデーション
        if not form.is_valid():
            # バリデーションNGの場合はアカウント登録画面のテンプレートを再表示
            return render(request, 'accounts/register.html', {'form': form})

        # 保存する前に一旦取り出す
        user = form.save(commit=False)
        # パスワードをハッシュ化してセット
        user.set_password(form.cleaned_data['password'])
        # ユーザーオブジェクトを保存
        user.save()

        # ログイン処理（取得した Userオブジェクトをセッションに保存 & Userデータを更新）
        auth_login(request, user)

        return redirect(settings.LOGIN_REDIRECT_URL)


register = RegisterView.as_view()


class LoginView(View):
    def get(self, request, *args, **kwargs):
        """GETリクエスト用のメソッド"""
        # すでにログインしている場合はショップ画面へリダイレクト
        if request.user.is_authenticated:
            return redirect(reverse('shop:index'))

        context = {
            'form': LoginForm(),
        }
        # ログイン画面用のテンプレートに値が空のフォームをレンダリング
        return render(request, 'accounts/login.html', context)

    def post(self, request, *args, **kwargs):
        """POSTリクエスト用のメソッド"""
        # リクエストからフォームを作成
        form = LoginForm(request.POST)
        # バリデーション（ユーザーの認証も合わせて実施）
        if not form.is_valid():
            # バリデーションNGの場合はログイン画面のテンプレートを再表示
            return render(request, 'accounts/login.html', {'form': form})

        # ユーザーオブジェクトをフォームから取得
        user = form.get_user()

        # ログイン処理（取得したユーザーオブジェクトをセッションに保存 & ユーザーデータを更新）
        auth_login(request, user)

        # ログイン後処理（ログイン回数を増やしたりする。本来は user_logged_in シグナルを使えばもっと簡単に書ける）
        user.post_login()

        # ロギング
        logger.info("User(id={}) has logged in.".format(user.id))

        # フラッシュメッセージを画面に表示
        messages.info(request, "ログインしました。")

        # ショップ画面にリダイレクト
        return redirect(reverse('shop:index'))


login = LoginView.as_view()


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # ロギング
            logger.info("User(id={}) has logged out.".format(request.user.id))
            # ログアウト処理
            auth_logout(request)

        # フラッシュメッセージを画面に表示
        messages.info(request, "ログアウトしました。")

        return redirect(reverse('accounts:login'))


logout = LogoutView.as_view()


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = ProfileForm(None, instance=request.user)
        context = {
            'form': form,
        }
        return render(request, 'accounts/profile.html', context)

    def post(self, request, *args, **kwargs):
        logger.info("You're in post!!!")

        # フォームを使ってバリデーション
        form = ProfileForm(request.POST, instance=request.user)
        if not form.is_valid():
            return render(request, 'accounts/profile.html', {'form': form})

        # 変更を保存
        form.save()

        # フラッシュメッセージを画面に表示
        messages.info(request, "プロフィールを更新しました。")
        return redirect('/accounts/profile/')


profile = ProfileView.as_view()

python/django/django-book-mysite-sample/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}ログイン{% endblock %}

{% block extra_css %}
<style type="text/css">
    .container > .grid {
        height: 100%;
    }

    .column {
        max-width: 400px;
    }

    p.red.message {
        color: #db2828;
        margin: 0.8em 0 0 0.8em;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <img src="{% static 'images/logo.png' %}" class="image">
            <div class="content">ログイン</div>
        </h2>

        <form action="{% url 'accounts:login' %}" method="post" class="ui form">
            <div class="ui stacked segment">
                {# --- 全体エラーメッセージ --- #}
                {% if form.non_field_errors %}
                <div class="ui red message">
                    <div class="header">エラー</div>
                    <ul class="list">
                        {% for non_field_error in form.non_field_errors %}
                        <li>{{ non_field_error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% for field in form %}
                <div class="field{% if field.errors %} error{% endif %}">
                    {# --- 入力フィールド --- #}
                    <div class="ui input{% if field.errors %} error{% endif %}">
                        {{ field }}
                    </div>
                    {# --- 入力フィールドごとのエラーメッセージ（最初のエラーのみを表示） --- #}
                    {% if field.errors %}
                    <p class="red message">{{ field.errors.0 }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                {% csrf_token %}
                <button type="submit" class="ui fluid teal submit button">ログイン</button>
            </div>
        </form>

        <div class="ui message">
            <a href="{% url 'accounts:register' %}">新規ユーザー登録はこちら</a>
        </div>
    </div>
</div>
{% endblock %}

python/django/django-book-mysite-sample/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}プロフィール更新{% endblock %}

{% block extra_css %}
<style type="text/css">
    .container > .grid {
        height: 100%;
    }

    .column {
        max-width: 400px;
    }

    p.red.message {
        color: #db2828;
        margin: 0.8em 0 0 0.8em;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <img src="{% static 'images/logo.png' %}" class="image">
            <div class="content">プロフィール変更</div>
        </h2>

        <form action="" method="post" class="ui form">
            <div class="ui stacked segment">
                {# --- 全体エラーメッセージ --- #}
                {% if form.non_field_errors %}
                <div class="ui red message">
                    <div class="header">エラー</div>
                    <ul class="list">
                        {% for non_field_error in form.non_field_errors %}
                        <li>{{ non_field_error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% for field in form %}
                <div class="field{% if field.errors %} error{% endif %}">
                    {# --- 入力フィールド --- #}
                    <div class="ui input{% if field.errors %} error{% endif %}">
                        {{ field }}
                    </div>
                    {# --- 入力フィールドごとのエラーメッセージ（最初のエラーのみを表示） --- #}
                    {% if field.errors %}
                    <p class="red message">{{ field.errors.0 }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                {% csrf_token %}
                <button type="submit" class="ui fluid teal submit button">更新</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

python/django/django-book-mysite-sample/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}新規ユーザー登録{% endblock %}

{% block extra_css %}
    <style type="text/css">
        .container > .grid {
          height: 100%;
        }
        .column {
            max-width: 400px;
        }
        p.red.message {
            color: #db2828;
            margin: 0.8em 0 0 0.8em;
            text-align: left;
        }
    </style>
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <img src="{% static 'images/logo.png' %}" class="image">
            <div class="content">新規ユーザー登録</div>
        </h2>

        <form action="" method="post" class="ui form">
            <div class="ui stacked segment">
                {# --- 全体エラーメッセージ --- #}
                {% if form.non_field_errors %}
                <div class="ui red message">
                    <div class="header">エラー</div>
                    <ul class="list">
                        {% for non_field_error in form.non_field_errors %}
                        <li>{{ non_field_error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% for field in form %}
                <div class="field{% if field.errors %} error{% endif %}">
                    {# --- 入力フィールド --- #}
                    <div class="ui input{% if field.errors %} error{% endif %}">
                        {{ field }}
                    </div>
                    {# --- 入力フィールドごとのエラーメッセージ（最初のエラーのみを表示） --- #}
                    {% if field.errors %}
                    <p class="red message">{{ field.errors.0 }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                {% csrf_token %}
                <button type="submit" class="ui fluid teal submit button">ユーザー登録</button>
            </div>
        </form>

        <div class="ui message">
            <a href="{% url 'accounts:login' %}">ログインはこちら</a>
        </div>
    </div>
</div>
{% endblock %}