python/django/django-book-mysite-sample/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.detail, name='detail'),
    path('checkout/', views.checkout, name='checkout'),
]

python/django/django-book-mysite-sample/shop/models.py
from django.db import models


class Publisher(models.Model):
    """出版社モデル"""

    class Meta(object):
        db_table = 'publisher'

    name = models.CharField(verbose_name='出版社名', max_length=255)

    def __str__(self):
        return self.name


class Author(models.Model):
    """著者モデル"""

    class Meta(object):
        db_table = 'author'

    name = models.CharField(verbose_name='著者名', max_length=255)

    def __str__(self):
        return self.name


class Book(models.Model):
    """本モデル"""

    class Meta(object):
        db_table = 'book'

    title = models.CharField(verbose_name='タイトル', max_length=255)
    image = models.ImageField(verbose_name='画像', null=True, blank=True)
    publisher = models.ForeignKey(Publisher, verbose_name='出版社', on_delete=models.PROTECT)
    authors = models.ManyToManyField(Author, verbose_name='著者')
    price = models.PositiveIntegerField(verbose_name='価格', null=True, blank=True, default=0)
    description = models.TextField(verbose_name='概要', null=True, blank=True)
    publish_date = models.DateField(verbose_name='出版日', null=True, blank=True)

    def __str__(self):
        return self.title

python/django/django-book-mysite-sample/shop/views.py
import logging

import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import View

from .models import Book

logger = logging.getLogger(__name__)


class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        queryset = Book.objects.select_related('publisher').prefetch_related('authors').order_by('publish_date')
        keyword = request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(description__icontains=keyword)
            )
        context = {
            'keyword': keyword,
            'book_list': queryset,
        }
        return render(request, 'shop/book_list.html', context)


index = IndexView.as_view()


class DetailView(LoginRequiredMixin, View):
    def get(self, request, book_id, *args, **kwargs):
        book = Book.objects.get(pk=book_id)
        context = {
            'book': book,
            'stripe_pub_key': settings.STRIPE_PUBLISHABLE_KEY,
        }
        return render(request, 'shop/book_detail.html', context)


detail = DetailView.as_view()


class CheckoutView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        import time
        start_time = time.time()
        logger.info("User({}) posted the form.".format(request.user.id))

        stripe.api_key = settings.STRIPE_API_KEY
        token = request.POST['stripeToken']
        item_id = request.POST['item_id']
        book = get_object_or_404(Book, pk=item_id)

        try:
            charge = stripe.Charge.create(
                amount=book.price,
                currency='jpy',
                source=token,
                description=book.title,
            )
        except stripe.error.CardError as e:
            # The card has been declined
            return render(request, 'error.html', {
                'message': "Your payment cannot be completed. The card has been declined.",
            })

        logger.info("Charge[{}] created successfully.".format(charge.id))
        messages.info(request, "Your payment has been completed successfully.")
        logger.debug("Finished in {:.2f} secs.".format(time.time() - start_time))
        return render(request, 'shop/complete.html', {
            'charge': charge,
        })


checkout = CheckoutView.as_view()

python/django/django-book-mysite-sample/templates/shop/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}商品リスト{% endblock %}

{% block extra_css %}
<style type="text/css">
</style>
{% endblock %}

{% block content %}
商品詳細
<br>
<br>
<form action="{% url 'shop:checkout' %}" method="post">
    <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="{{ stripe_pub_key }}"
            data-label="クレジットカードで支払う"
            data-name="クレジットカード支払い"
            data-description="{{ book.title }}"
            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
            data-amount="{{ book.price }}"
            data-currency="jpy"
            data-locale="auto">
    </script>
    <input type="hidden" name="item_id" value="{{ book.id }}">
    {% csrf_token %}
</form>

{% endblock %}

python/django/django-book-mysite-sample/templates/shop/book_list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block page_title %}商品リスト{% endblock %}

{% block extra_css %}
<style type="text/css">
    .container > .grid {
        height: 100%;
    }

    .table {
        max-width: 400px;
    }

    .ui.grid > .column {
        padding-top: 0.3em !important;
        padding-bottom: 0.3em !important;
    }

    p.red.message {
        color: #db2828;
        margin: 0.8em 0 0 0.8em;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
<form method="get" action="{% url 'shop:index' %}" class="ui form">
    <div class="ui stacked segment">
        <div class="field">
            <div class="ui input">
                <input type="text" name="keyword" placeholder="キーワード" value="{{ keyword|default:'' }}">
            </div>
        </div>
        <button type="submit" class="ui fluid teal submit button">検索</button>
    </div>
</form>

<div class="ui four cards">
    {% for book in book_list %}
    <div class="ui card">
        <div class="image">
            {% if book.image %}
            <img src="{{ book.image.url }}">
            {% else %}
            <img src="{% static 'shop/images/no-image.png' %}">
            {% endif %}
        </div>
        <div class="content">
            <div class="header"><a href="{% url 'shop:detail' book.id %}">{{ book.title }}</a></div>
            <div class="ui divided list">
                <span class="item">
                    <div class="ui horizontal label">著　者</div>{{ book.authors.all.0 }}{% if book.authors.all.1 %}　他{% endif %}
                </span>
                <span class="item">
                    <div class="ui horizontal label">価　格</div>{{ book.price|default_if_none:0|intcomma }}円
                </span>
                <span class="item">
                    <div class="ui horizontal label">出版社</div>{{ book.publisher }}
                </span>
                <span class="item">
                    <div class="ui horizontal label">出版日</div>{{ book.publish_date|date:"Y年m月d日" }}
                </span>
                <span class="item">
                    <div class="ui horizontal label">詳　細</div>
                    <div class="description">{{ book.description|default:""|linebreaksbr|truncatechars_html:20 }}</div>
                </span>
            </div>
        </div>
        <div class="extra content">
            <a href="{% url 'shop:detail' book.id %}" class="ui right floated positive button">商品詳細</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

python/django/django-book-mysite-sample/templates/shop/complete.html
{% extends "base.html" %}

{% block page_title %}Complete{% endblock %}

{% block content %}
<span style="font-size: 0.7rem;">{{ charge }}</span>
{% endblock content %}