python/django/django-book-mysite-sample/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

python/django/django-book-mysite-sample/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.detail, name='detail'),
    path('checkout/', views.checkout, name='checkout'),
]

python/django/django-book-mysite-sample/templates/_message.html
{% block messages %}
{% if messages %}
<div class="ui relaxed divided list">
    {% for message in messages %}
    <div class="ui {% if message.tags %}{{ message.tags }}{% endif %} message">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endblock messages %}

python/django/django-book-mysite-sample/templates/base.html
<!doctype html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}{% endblock %}</title>

    {# --- css --- #}
    <link rel="stylesheet" href="{% static 'vendor/semantic/semantic.min.css' %}">
    <style type="text/css">
        body {
            background-color: #dadada;
        }
        body > .container {
            height: 100%;
        }
    </style>
    {% block extra_css %}{% endblock %}
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
<div class="ui container">
    {% include '_message.html' %}
    {% block content %}{% endblock %}
</div>

{# TODO #}
{% if user.is_authenticated %}
<a href="{% url 'accounts:logout' %}">ログアウト</a> | <a href="{% url 'accounts:profile' %}">プロフィール</a> | <a href="{% url 'shop:index' %}">ショップ</a>
{% endif %}

{# --- js --- #}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'vendor/semantic/semantic.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>