python/django/AIのWebアプリを作ろう/aipj/aipj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cnnapp/', include('cnnapp.urls')),
]

python/django/AIのWebアプリを作ろう/aipj/cnnapp/urls.py
from django.urls import path
from . import views
 
app_name ='cnnapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

python/django/AIのWebアプリを作ろう/aipj/cnnapp/models.py
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import InputLayer, Dense, Activation, Dropout, Flatten
 
from django.db import models
import numpy as np
from PIL import Image
import io, base64
 
 
class Pict(models.Model):
  image = models.ImageField(upload_to='picture')
 
  IMAGE_SIZE = 32
  MODEL_FILE_PATH = './carbike/trainedmodel/model_cnn_cifer.h5'
  CLASSES = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
  NUM_CLASSES = len(CLASSES)
 
  def predict(self):
 
    # create model
    model = Sequential()
    model.add(InputLayer(input_shape=(32,32,3)))
 
    model.add(Conv2D(32,3))
    model.add(Activation('relu'))
 
    model.add(Conv2D(32,3))
    model.add(Activation('relu'))
    model.add(MaxPool2D(pool_size=(2,2)))
 
    model.add(Conv2D(64,3))
    model.add(Activation('relu'))
    model.add(MaxPool2D(pool_size=(2,2)))
 
    model.add(Flatten())
    model.add(Dense(1024))
    model.add(Activation('relu'))
 
    model.add(Dropout(0.5))
 
    model.add(Dense(self.NUM_CLASSES, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=["accuracy"])
    model.summary()
 
    # predict
    img_data = self.image.read()
    img_bin = io.BytesIO(img_data)
    image = Image.open(img_bin)
    image = image.convert("RGB")
    image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
    data = np.asarray(image) / 255.0
    X = []
    X.append(data)
    X = np.array(X)
 
    result = model.predict([X])[0]
    predicted = result.argmax()
    rate = int(result[predicted] * 100)
 
    print(self.CLASSES[predicted], rate)
    return self.CLASSES[predicted], rate
 
 
  def image_src(self):
    with self.image.open() as img:
      base64_img = base64.b64encode(img.read()).decode()
 
      return 'data:' + img.file.content_type + ';base64,' + base64_img

python/django/AIのWebアプリを作ろう/aipj/cnnapp/forms.py
from django import forms

class PictForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

python/django/AIのWebアプリを作ろう/aipj/cnnapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from .forms import PictForm
from .models import Pict

def index(request):
    template = loader.get_template('cnnapp/index.html')
    context = {'form': PictForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == 'POST':
        return
        redirect('cnnapp:index')

    form = PictForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Form is illegal.')

    pict = Pict(image=form.cleaned_data['image'])
    predicted, rate = pict.predict()

    template = loader.get_template('cnnapp/result.html')

    context = {
        'pict_name': pict.image.name,
        'pict_data': pict.image_src(),
        'predicted': predicted,
        'rate': rate,
    }

    return HttpResponse(template.render(context, request))

python/django/AIのWebアプリを作ろう/aipj/cnnapp/templates/cnnapp/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'cnnapp/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>画像分類AI | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">画像分類AI</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

python/django/AIのWebアプリを作ろう/aipj/cnnapp/templates/cnnapp/index.html
{% extends 'cnnapp/base.html' %}
{% block title %}画像分類AI{% endblock %}

{% block content %}
<div>
    <br>
    <p>画像ファイルを指定し、分類実行ボタンをクリックしてください。</p>
    <form action="{% url 'cnnapp:predict' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <div class="custom-file">
            {{ form.image }}
            <label class="custom-file-label" for="customFile">
                ファイル指定
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">分類実行</button>
    </form> 
</div>
{% endblock %}

python/django/AIのWebアプリを作ろう/aipj/cnnapp/templates/cnnapp/result.html
{% extends 'cnnapp/base.html' %}
{% block title %}画像分類結果{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">画像分類結果</h4>

    <table class='table'>
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ pict_name }}</td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td><img class='preview-img' src={{ pict_data }} ></img></td>
                </tr>
            <tr>
                <td>分類名</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>分類確率</td>
                <td>{{ rate }} %</td>
            </tr>
        </tbody>
    </table>

    <a href = "{% url 'cnnapp:index' %}" class="btn btn-primary">画像指定に戻る</a>

</div>
{% endblock %}